server:
  port: 8080

# mysql
spring:
  mvc:
      static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      maxFileSize: 50MB
      maxRequestSize: 20MB
  session:
    timeout:600s
  jackson:
    date-format: yyyy-MM-dd
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vege_knowledge?useUnicode=true&characterEncoding=UTF8&serverTimezone=PRC
    username: vegesa
    password: vegesa
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    check-template: true
    # 关闭模板缓存，便于调试
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    mode: LEGACYHTML5
